/// Participant ID validation for the PostureGuard study.
///
/// Paste [ParticipantId] into the app (suggested home:
/// `lib/services/participant_id.dart`) and validate on the ID entry screen.
/// A mistyped ID would otherwise produce sessions that can never be joined
/// to the participant's consent record — orphan data that is invisible at
/// collection time and useless at analysis time.
///
/// This mirrors the generator in `study/participant_onboarding.html`
/// character for character. Run this file directly to self-test:
///
///     dart run study/participant_id_validator.dart
library;

class ParticipantId {
  /// Crockford Base32: no I, L, O or U, so 1/I and 0/O cannot be confused.
  static const String alphabet = '0123456789ABCDEFGHJKMNPQRSTVWXYZ';

  /// 7 random characters + 1 Luhn mod-32 check character.
  static const int bodyLength = 8;

  /// Accepts what a participant actually types: any case, with or without
  /// the `PG-` prefix and the dashes, and with the characters Crockford
  /// says to fold (I/L → 1, O → 0).
  ///
  /// Returns the canonical `PG-XXXX-XXXX` form, or null if the ID is not
  /// well formed or fails its checksum.
  static String? normalize(String input) {
    var s = input.toUpperCase().replaceAll(RegExp(r'[\s\-–—_]'), '');

    if (s.startsWith('PG')) s = s.substring(2);

    s = s.replaceAll('I', '1').replaceAll('L', '1').replaceAll('O', '0');

    if (s.length != bodyLength) return null;
    for (final unit in s.codeUnits) {
      if (!alphabet.contains(String.fromCharCode(unit))) return null;
    }
    if (!_checksumHolds(s)) return null;

    return 'PG-${s.substring(0, 4)}-${s.substring(4)}';
  }

  /// True when [input] is a well-formed ID with a valid check character.
  static bool isValid(String input) => normalize(input) != null;

  /// Luhn mod N over the full body, check character included.
  static bool _checksumHolds(String body) {
    const n = 32;
    var factor = 1;
    var sum = 0;

    for (var i = body.length - 1; i >= 0; i--) {
      final index = alphabet.indexOf(body[i]);
      if (index < 0) return false;

      var addend = factor * index;
      factor = (factor == 1) ? 2 : 1;
      addend = (addend ~/ n) + (addend % n);
      sum += addend;
    }

    return sum % n == 0;
  }
}

// ─────────────────────────── self-test ───────────────────────────

void main() {
  var passed = 0;
  var failed = 0;

  void check(String label, bool condition) {
    if (condition) {
      passed++;
    } else {
      failed++;
      print('  FAIL: $label');
    }
  }

  // Generated by study/participant_onboarding.html.
  const valid = [
    'PG-E8XM-H06Y',
    'PG-AZ11-1H5D',
    'PG-GZBS-Q3SC',
    'PG-PS94-60ZS',
    'PG-8QKZ-X35B',
  ];

  for (final id in valid) {
    check('$id accepted', ParticipantId.isValid(id));
    check('$id canonical', ParticipantId.normalize(id) == id);
  }

  // Input forms a participant might realistically type.
  check('lowercase', ParticipantId.normalize('pg-e8xm-h06y') == 'PG-E8XM-H06Y');
  check('no dashes', ParticipantId.normalize('PGE8XMH06Y') == 'PG-E8XM-H06Y');
  check('no prefix', ParticipantId.normalize('E8XMH06Y') == 'PG-E8XM-H06Y');
  check('spaces', ParticipantId.normalize(' PG E8XM H06Y ') == 'PG-E8XM-H06Y');
  check('O typed for zero',
      ParticipantId.normalize('PG-E8XM-HO6Y') == 'PG-E8XM-H06Y');
  check('I typed for one',
      ParticipantId.normalize('PG-AZII-1H5D') == 'PG-AZ11-1H5D');

  // Rejections.
  check('empty rejected', !ParticipantId.isValid(''));
  check('too short rejected', !ParticipantId.isValid('PG-E8XM-H06'));
  check('too long rejected', !ParticipantId.isValid('PG-E8XM-H06YQ'));
  check('bad character rejected', !ParticipantId.isValid('PG-E8X!-H06Y'));
  check('wrong checksum rejected', !ParticipantId.isValid('PG-E8XM-H06Z'));
  check('random string rejected', !ParticipantId.isValid('HELLOTHERE'));

  // Every single-character substitution must be caught.
  var substitutionsTried = 0;
  var substitutionsMissed = 0;
  for (final id in valid) {
    final body = id.replaceAll('-', '').substring(2);
    for (var pos = 0; pos < body.length; pos++) {
      for (final ch in ParticipantId.alphabet.split('')) {
        if (ch == body[pos]) continue;
        substitutionsTried++;
        final typo = body.replaceRange(pos, pos + 1, ch);
        if (ParticipantId.isValid(typo)) substitutionsMissed++;
      }
    }
  }
  check('all $substitutionsTried single-character typos caught',
      substitutionsMissed == 0);

  // Adjacent transpositions: Luhn mod N catches the great majority.
  var transpositionsTried = 0;
  var transpositionsMissed = 0;
  for (final id in valid) {
    final body = id.replaceAll('-', '').substring(2);
    for (var pos = 0; pos < body.length - 1; pos++) {
      if (body[pos] == body[pos + 1]) continue;
      transpositionsTried++;
      final swapped =
          body.replaceRange(pos, pos + 2, '${body[pos + 1]}${body[pos]}');
      if (ParticipantId.isValid(swapped)) transpositionsMissed++;
    }
  }
  check('most of $transpositionsTried transpositions caught',
      transpositionsMissed <= transpositionsTried * 0.05);

  print('');
  print('$passed passed, $failed failed');
  print('single-character typos caught: '
      '${substitutionsTried - substitutionsMissed}/$substitutionsTried');
  print('transpositions caught: '
      '${transpositionsTried - transpositionsMissed}/$transpositionsTried');
}
